### PR TITLE
Put pages in their own directories to hide html extension in the url bar

### PR DESCRIPTION
**Pull request by kylesferrazza**

### CODE REVIEW

**Comment by aliceyoung9** [comment]
Won't this mean that anyone working on a local copy will need to have the handful of HTML/CSS files here served to immediately preview style changes?

**Comment by kylesferrazza** [comment]
Updated to use relative links so style changes can be previewed without serving locally.

**Comment by jaronoff97** [comment]
How was this tested? @kylesferrazza

**Comment by kylesferrazza** [comment]
Open index.html in chrome and click any link on the page and then click the index.html for that directory

**Comment by aliceyoung9** [comment]
I mean, this worked on my machine. Who's smashing that merge button?

**Comment by kylesferrazza** [comment]
Closed in favor of #39

**Pull request closed without merging**
